[IV-24-25] Propuesta objetivo 0
mrh117/proyectoupgrade pull request #1
Opened 2024-09-27 08:58 UTC by mrh117

Pull request del primer objetivo

2024-09-28 08:22 UTC, JJ commented
> * [x]  ¿Se trata de un problema real del que se tenga conocimiento personal?
>       Sí, el problema planteado me afecta y se basa e mi experiencia
> 
>     * [x]  ¿Se trata de un problema que para solucionar requiera el despliegue
>       de una aplicación en la nube?
>       Sí, ya que para el funcionamiento adecuado de las opciones de personalización, necesitamos contar con múltiples modelos predefinidos, lo que nos creará la necesitad de almacenar esos datos en un sistema adecuado para ello, como la nube
> 
>     * [ ]  ¿La solución requiere una cierta cantidad de lógica de negocio, en vez
>       solucionarse sólo almacenando y buscando?
>       Aquí tengo algunas dudas, ya que la lógica de la aplicación se basaría en la búsqueda del programa más adecuado mediante el procesamiento de los datos y objetivos del usuario, así como de lógica para adaptarse al progreso del mismo y realizar las acciones correspondientes.
> 
>     * [ ]  ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el
>       `README`?
>       De momento no, pero me gustaría entregar antes para ver si la idea es factible en clase, y luego después de clase me pongo con ello

Esa es una respuesta honesta y totalmente adecuada. Tienes toda la razón del mundo.

2024-09-28 08:28 UTC, JJ requested changes
Es posible que un problema de alguien que quiera entrenar autónomamente sea no saber qué entrenamientos hacer que cumplan una serie de condiciones. Si son condiciones que no están correlacionadas, puede que para resolverlo haga falta una lógica de negocio sustancial: el problema de la mochila, por ejemplo. Si hay alguna forma de encontrar los entrenamientos online, también puede ser un problema extraerlos de una página semiestructurada. Por favor, considera todo esto como posibles alternativas (o cualquier otra que se te pueda ocurrir)

2024-09-28 08:28 UTC, JJ commented on extra
> +
Por favor, no incluyáis "ruido" en los PR, que hay que revisarlos todos.

2024-09-28 08:28 UTC, JJ commented on README.md
> +una herramienta que le ayude a encontrar tanto la regularidad como la motivación con respecto a sus entrenamientos. Por tanto nuestro proyecto tratará de resolver esta disyuntiva,
"necesita una herramienta" no expresa realmente una necesidad. 
El problema es, como se indica en [errores frecuentes](https://github.com/JJ/IV-/blob/master/errores/objetivo-0.md#en-el-contenido), que

> Los deseos del cliente son órdenes, y eso significa que si el cliente quiere que vuestra aplicación haga algo, tendréis que testear que efectivamente lo hace. Si el problema es maximizar ventas, tendréis que examinar cuales son las ventas con el método actual (o aleatorio, lo que sea) y después con vuestro algoritmo, y ver que es superior estricto. Si queréis predecir, tendréis que programar vosotros un algoritmo que prediga y comprobar con datos que efectivamente lo hace.

Y eso significa que tendrás que tener una función que procese los datos y devuelva la "regularidad" y otra que devuelva la "motivación". No solo eso, que compruebe que con tu método ambas funciones devuelven mejores valores que con la función anterior.

Si es posible evaluar ambas cosas de forma objetiva y sin conexión a datos externos (o datos que tenga que incluir el usuario), podría ser válido.

2024-09-28 08:28 UTC, JJ commented on README.md
> +a través de ofrecerle a nuestro cliente una serie de entranamientos y metas con cierto grado de adaptación a sus objetivos y capacidades, además de conseguir motivar al cliente
Estás describiendo una solución, no un problema. Estás asumiendo también que "ofrecer entrenamientos" mejora la motivación. Pero en todo caso en ingeniería hay que comprobar que se resuelve el problema.

2024-09-29 18:13 UTC, mrh117 commented
> Es posible que un problema de alguien que quiera entrenar autónomamente sea no saber qué entrenamientos hacer que cumplan una serie de condiciones. Si son condiciones que no están correlacionadas, puede que para resolverlo haga falta una lógica de negocio sustancial: el problema de la mochila, por ejemplo. Si hay alguna forma de encontrar los entrenamientos online, también puede ser un problema extraerlos de una página semiestructurada. Por favor, considera todo esto como posibles alternativas (o cualquier otra que se te pueda ocurrir)

Buenas @JJ, en cuanto a lo de extraer los entrenamientos de una página online externa, qué objetivo tiene eso? ; ¿para que esa búsqueda y procesamiento de los datos sea uno de los componentes que formen la lógica de negocio?¿O simplemente para tener un lugar desde donde obtener esos entrenamientos? Porque si es la segunda, yo había pensado incluirlos yo mismo en la aplicación, y serían esos datos parte de los que almacenaría en la nube. Si es la primera, sí que podría estudiar hacerlo pero tendría que buscar si existen los recursos para hacerlo. Quedo pendiente de su aclaración, gracias.

2024-09-29 18:29 UTC, mrh117 commented on README.md
> +una herramienta que le ayude a encontrar tanto la regularidad como la motivación con respecto a sus entrenamientos. Por tanto nuestro proyecto tratará de resolver esta disyuntiva,
¿Y hasta qué punto se puede considerar un dato objetivo? Porque recuerdo lo que hablamos sobre que lo ideal sería tomarlos del entorno físico, pero no valdría un sistema en el que el cliente responda si ha completado el entrenamiento propuesto? Al fin y al cabo, con casi cualquier sistema se puede hacer un mal uso del él, y no por ello no es viable si se usa correctamente. 
Aún así, en caso de que mi sistema necesitara estar más integrado durante el entrenamiento, he pensado en la posibilidad de crear algún protocolo para que el cliente demuestre ( o al menos le sea más difícil engañar al sistema) que está entrenando, por ejemplo, con que obligue a que la aplicación esté abierta, o que tenga que ir marcando como completados manualmente cada uno de los sets de la rutina, etc.

2024-09-30 06:40 UTC, JJ commented
> > Es posible que un problema de alguien que quiera entrenar autónomamente sea no saber qué entrenamientos hacer que cumplan una serie de condiciones. Si son condiciones que no están correlacionadas, puede que para resolverlo haga falta una lógica de negocio sustancial: el problema de la mochila, por ejemplo. Si hay alguna forma de encontrar los entrenamientos online, también puede ser un problema extraerlos de una página semiestructurada. Por favor, considera todo esto como posibles alternativas (o cualquier otra que se te pueda ocurrir)
> 
> Buenas @JJ, en cuanto a lo de extraer los entrenamientos de una página online externa, qué objetivo tiene eso? ; ¿para 

¿Qué objetivo tiene que alguien los meta a mano?

> que esa búsqueda y procesamiento de los datos sea uno de los componentes que formen la lógica de negocio?¿O 

Claro.

> simplemente para tener un lugar desde donde obtener esos entrenamientos? Porque si es la segunda, yo había 

Si no lo tienes, ¿cómo creas los entrenamientos?

> pensado incluirlos yo mismo en la aplicación, y serían esos datos parte de los que almacenaría en la nube. Si es la primera, sí que podría estudiar hacerlo pero tendría que buscar si existen los recursos para hacerlo. Quedo pendiente de su aclaración, gracias.

Se dice claramente que no se deben introducir una gran cantidad de datos por parte del usuario (o por tu parte, que es lo mismo)

2024-09-30 06:43 UTC, JJ commented on README.md
> +una herramienta que le ayude a encontrar tanto la regularidad como la motivación con respecto a sus entrenamientos. Por tanto nuestro proyecto tratará de resolver esta disyuntiva,
Se trata simplemente de que se pueda comprobar automáticamente si se ha resuelto un problema o no, es decir, si puedes ejecutar un test que lo haga. En desarrollo ágil se usa integración (y despliegue) continuo, y si hay que pararse para preguntarle al usuario (o para leer de un dispositivo físico) si algo ha funcionado o no, no se pueden hacer los tests automáticos.
Puedes crear todos los protocolos que quieras (y requerir miles de datos al usuario *en contra de lo que se considera válido en esta asignatura*) pero aún así no vas a poder testear si lo que has hecho resuelve el problema o no. Ingeniería del software es *resolver* problemas, no escribir código.

2024-10-07 05:41 UTC, JJ commented
Si está listo para revisión, por favor pedidlo explícitamente.

2024-10-10 10:10 UTC, JJ commented
¿Está listo o no?

2024-10-11 12:08 UTC, mrh117 commented
@JJ Ya he presentado el nuevo README con la propuesta nueva

2024-10-11 12:25 UTC, JJ approved these changes
Por favor, incluye enlaces a las páginas y documentos de los que vas a extraer información, y quizás también la lógica de negocio, porque la persona que trabaje en el objetivo 1 la necesitará.

2024-10-11 12:25 UTC, JJ commented on README.md
> +  a través de ofrecerle a nuestro cliente una serie de entranamientos y metas con cierto grado de adaptación a sus objetivos y capacidades, además de conseguir motivar al cliente
typo: entr*a*namientos

2024-10-12 01:17 UTC, mrh117 commented
> Por favor, incluye enlaces a las páginas y documentos de los que vas a extraer información, y quizás también la lógica de negocio, porque la persona que trabaje en el objetivo 1 la necesitará.

Añadido. Hago ya el merge?

2024-10-12 06:30 UTC, JJ commented
Está aprobado, hazlo cuando quieras.

2024-10-17 06:41 UTC, merged